# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.27
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
enable_checklog_odoo: false
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_test_flavor: Odoo
odoo_version: 16.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description:
  Packed Picking Module for Odoo 16 is a module for automating the creation and packing
  of goods movements in inventory. Includes _create_packed_picking and wizard for easy
  management of packing via the Packed Goods menu. Compliant with OCA standards and
  tested.
repo_name: Packed Picking
repo_slug: test_task_packed_picking
repo_website: https://github.com/tendil/test_task_packed_picking
use_pyproject_toml: false
use_ruff: false
